### ISSUE TITLE
How could we add precipitation forecast in your neural-lam?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [joeloskarsson/neural-lam#12]
I've send email to you asking about removing precipitation from GraphCast origional codes,sir.
Thank you for your quick reply. In the email you explained the precipitation part is difficult due to ERA5 
precipitation is not accurate enough. So, as in a specific region like China, we got  high quelity precipitation
reanalysis data. Maybe, we could use these precipitation data instead of ERA5 precipitation to make the forecast better.

Now, how could we add the precipitation part in your neural-lam codes?
Thank you.

**Comment by joeloskarsson** [comment]
Hi,
You should be able to add in a field such as total precipitation together with all the other modeled variables. So in practice, compiling a training dataset including this field, and modifying the list of variables in `constants.py` to match the ones in your data. 

Some adaptation would also be needed to run for your specific region, but that is not related to modeling precipitation specifically (see https://github.com/joeloskarsson/neural-lam/issues/4).

**Comment by sadamov** [comment]
Hi, we are using hourly precip sums for 2.2km precipitation forecast in our fork: https://github.com/MeteoSwiss/neural-lam. Maybe the zarr-based dataloader for model level data is useful on a technical level. We have a bug in the data-prep (hourly sums are wrongly calculated), so the predictions are off. Still, if you think about adding Precip to your input channels maybe this helps.

**Comment by joeloskarsson** [comment]
@weatherforecasterwhai Does this answer your question? Can I close the issue?

**Comment by weatherforecasterwhai** [comment]
Yes, Thank you!



At 2024-03-13 16:05:15, "Joel Oskarsson" ***@***.***> wrote:

@weatherforecasterwhai Does this answer your question? Can I close the issue?
